import type { MetricDefinition, SectionDefinition, SourceId } from '../types.js'

export const SECTION_DEFINITIONS: SectionDefinition[] = [
  {
    id: 'internet-scale',
    title: 'Internet Scale',
    description: 'Global growth and internet footprint counters.',
  },
  {
    id: 'activity',
    title: 'Activity Right Now',
    description: 'Live usage and communication intensity across the web.',
  },
  {
    id: 'social',
    title: 'Social Platforms',
    description: 'Audience size and usage in major social communities.',
  },
  {
    id: 'infrastructure',
    title: 'Devices and Impact',
    description: 'Hardware sales, traffic, and environmental impact.',
  },
  {
    id: 'worldometers',
    title: 'Worldometers',
    description: 'Worldometers global activity counters sampled hourly.',
  },
]

export const METRIC_REGISTRY: MetricDefinition[] = [
  {
    id: 'internet_users',
    rel: 'internet_users',
    sourceId: 'internetlivestats',
    label: 'Internet Users',
    description: 'People online worldwide.',
    category: 'internet-scale',
    accent: '#38bdf8',
    fallbackMode: 'absolute',
    fallbackBaseValue: 5_450_000_000,
    fallbackRatePerSecond: 2.3,
  },
  {
    id: 'websites_total',
    rel: 'websites',
    sourceId: 'internetlivestats',
    label: 'Websites',
    description: 'Total number of websites online.',
    category: 'internet-scale',
    accent: '#22d3ee',
    fallbackMode: 'absolute',
    fallbackBaseValue: 1_180_000_000,
    fallbackRatePerSecond: 8,
  },
  {
    id: 'emails_sent_today',
    rel: 'em/today',
    sourceId: 'internetlivestats',
    label: 'Emails Sent Today',
    description: 'Emails sent from midnight to now.',
    category: 'activity',
    accent: '#c084fc',
    fallbackMode: 'daily',
    fallbackBaseValue: 0,
    fallbackRatePerSecond: 4_166_667,
  },
  {
    id: 'google_searches_today',
    rel: 'google_searches/today',
    sourceId: 'internetlivestats',
    label: 'Google Searches Today',
    description: 'Search queries made on Google today.',
    category: 'activity',
    accent: '#f472b6',
    fallbackMode: 'daily',
    fallbackBaseValue: 0,
    fallbackRatePerSecond: 162_000,
  },
  {
    id: 'blog_posts_today',
    rel: 'blog_posts/today',
    sourceId: 'internetlivestats',
    label: 'Blog Posts Today',
    description: 'Blog posts published so far today.',
    category: 'activity',
    accent: '#818cf8',
    fallbackMode: 'daily',
    fallbackBaseValue: 0,
    fallbackRatePerSecond: 80,
  },
  {
    id: 'tweets_today',
    rel: 'tweets/today',
    sourceId: 'internetlivestats',
    label: 'Tweets Today',
    description: 'Tweets posted from midnight to now.',
    category: 'activity',
    accent: '#60a5fa',
    fallbackMode: 'daily',
    fallbackBaseValue: 0,
    fallbackRatePerSecond: 5_800,
  },
  {
    id: 'youtube_videos_today',
    rel: 'youtube_videos/today',
    sourceId: 'internetlivestats',
    label: 'YouTube Videos Today',
    description: 'Videos watched on YouTube today.',
    category: 'activity',
    accent: '#f87171',
    fallbackMode: 'daily',
    fallbackBaseValue: 0,
    fallbackRatePerSecond: 57_800,
  },
  {
    id: 'instagram_photos_today',
    rel: 'instagram_photos/today',
    sourceId: 'internetlivestats',
    label: 'Instagram Photos Today',
    description: 'Photos uploaded to Instagram today.',
    category: 'activity',
    accent: '#fb7185',
    fallbackMode: 'daily',
    fallbackBaseValue: 0,
    fallbackRatePerSecond: 1_100,
  },
  {
    id: 'tumblr_posts_today',
    rel: 'tumblr_posts/today',
    sourceId: 'internetlivestats',
    label: 'Tumblr Posts Today',
    description: 'Tumblr posts created today.',
    category: 'activity',
    accent: '#a78bfa',
    fallbackMode: 'daily',
    fallbackBaseValue: 0,
    fallbackRatePerSecond: 23,
  },
  {
    id: 'facebook_active_users',
    rel: 'facebook_users',
    sourceId: 'internetlivestats',
    label: 'Facebook Active Users',
    description: 'Active users on Facebook.',
    category: 'social',
    accent: '#3b82f6',
    fallbackMode: 'absolute',
    fallbackBaseValue: 3_100_000_000,
    fallbackRatePerSecond: 1.1,
  },
  {
    id: 'google_plus_active_users',
    rel: 'google_plus_users',
    sourceRel: 'google_users',
    sourceId: 'internetlivestats',
    label: 'Google+ Active Users',
    description: 'Active users on Google+.',
    category: 'social',
    accent: '#f97316',
    fallbackMode: 'absolute',
    fallbackBaseValue: 450_000_000,
    fallbackRatePerSecond: 0.05,
  },
  {
    id: 'twitter_active_users',
    rel: 'twitter_users',
    sourceId: 'internetlivestats',
    label: 'Twitter Active Users',
    description: 'Active users on Twitter.',
    category: 'social',
    accent: '#0ea5e9',
    fallbackMode: 'absolute',
    fallbackBaseValue: 620_000_000,
    fallbackRatePerSecond: 0.35,
  },
  {
    id: 'pinterest_active_users',
    rel: 'pinterest_users',
    sourceId: 'internetlivestats',
    label: 'Pinterest Active Users',
    description: 'Active users on Pinterest.',
    category: 'social',
    accent: '#ef4444',
    fallbackMode: 'absolute',
    fallbackBaseValue: 500_000_000,
    fallbackRatePerSecond: 0.2,
  },
  {
    id: 'skype_calls_today',
    rel: 'skype_calls/today',
    sourceId: 'internetlivestats',
    label: 'Skype Calls Today',
    description: 'Skype calls placed so far today.',
    category: 'social',
    accent: '#38bdf8',
    fallbackMode: 'daily',
    fallbackBaseValue: 0,
    fallbackRatePerSecond: 1_750,
  },
  {
    id: 'websites_hacked_today',
    rel: 'websites_hacked/today',
    sourceId: 'internetlivestats',
    label: 'Websites Hacked Today',
    description: 'Sites reportedly hacked so far today.',
    category: 'infrastructure',
    accent: '#f43f5e',
    fallbackMode: 'daily',
    fallbackBaseValue: 0,
    fallbackRatePerSecond: 0.35,
  },
  {
    id: 'computers_sold_today',
    rel: 'computers_sold/today',
    sourceId: 'internetlivestats',
    label: 'Computers Sold Today',
    description: 'Computers sold worldwide today.',
    category: 'infrastructure',
    accent: '#22c55e',
    fallbackMode: 'daily',
    fallbackBaseValue: 0,
    fallbackRatePerSecond: 5.8,
  },
  {
    id: 'smartphones_sold_today',
    rel: 'smartphones_sold/today',
    sourceId: 'internetlivestats',
    label: 'Smartphones Sold Today',
    description: 'Smartphones sold worldwide today.',
    category: 'infrastructure',
    accent: '#14b8a6',
    fallbackMode: 'daily',
    fallbackBaseValue: 0,
    fallbackRatePerSecond: 46.3,
  },
  {
    id: 'tablets_sold_today',
    rel: 'tablets_sold/today',
    sourceId: 'internetlivestats',
    label: 'Tablets Sold Today',
    description: 'Tablets sold worldwide today.',
    category: 'infrastructure',
    accent: '#84cc16',
    fallbackMode: 'daily',
    fallbackBaseValue: 0,
    fallbackRatePerSecond: 2.3,
  },
  {
    id: 'internet_traffic_today',
    rel: 'internet_traffic/today',
    sourceId: 'internetlivestats',
    label: 'Internet Traffic Today',
    description: 'Data moved over the internet today.',
    category: 'infrastructure',
    unit: 'GB',
    accent: '#f59e0b',
    fallbackMode: 'daily',
    fallbackBaseValue: 0,
    fallbackRatePerSecond: 5_900,
  },
  {
    id: 'internet_power_today',
    rel: 'power_internet/today',
    sourceId: 'internetlivestats',
    label: 'Internet Electricity Used',
    description: 'Electricity consumed by internet activity today.',
    category: 'infrastructure',
    unit: 'MWh',
    accent: '#a3e635',
    fallbackMode: 'daily',
    fallbackBaseValue: 0,
    fallbackRatePerSecond: 5.5,
  },
  {
    id: 'internet_co2_today',
    rel: 'co2_internet/today',
    sourceId: 'internetlivestats',
    label: 'Internet CO2 Emissions',
    description: 'Estimated internet-related CO2 emissions today.',
    category: 'infrastructure',
    unit: 'tons',
    accent: '#fb7185',
    fallbackMode: 'daily',
    fallbackBaseValue: 0,
    fallbackRatePerSecond: 1.5,
  },
  {
    id: 'wm_current_population',
    rel: 'wm_current_population',
    sourceRel: 'current_population',
    sourceId: 'worldometers',
    label: 'World Population',
    description: 'Current estimated world population.',
    category: 'worldometers',
    accent: '#22d3ee',
    fallbackMode: 'absolute',
    fallbackBaseValue: 8_200_000_000,
    fallbackRatePerSecond: 2.6,
  },
  {
    id: 'wm_births_today',
    rel: 'wm_births_today',
    sourceRel: 'births_today',
    sourceId: 'worldometers',
    label: 'Births Today',
    description: 'Estimated births since midnight.',
    category: 'worldometers',
    accent: '#fbbf24',
    fallbackMode: 'daily',
    fallbackBaseValue: 0,
    fallbackRatePerSecond: 4.6,
  },
  {
    id: 'wm_deaths_today',
    rel: 'wm_deaths_today',
    sourceRel: 'dth1s_today',
    sourceId: 'worldometers',
    label: 'Deaths Today',
    description: 'Estimated deaths since midnight.',
    category: 'worldometers',
    accent: '#fb7185',
    fallbackMode: 'daily',
    fallbackBaseValue: 0,
    fallbackRatePerSecond: 2.1,
  },
  {
    id: 'wm_growth_today',
    rel: 'wm_growth_today',
    sourceRel: 'absolute_growth',
    sourceId: 'worldometers',
    label: 'Population Growth Today',
    description: 'Estimated net growth since midnight.',
    category: 'worldometers',
    accent: '#34d399',
    fallbackMode: 'daily',
    fallbackBaseValue: 0,
    fallbackRatePerSecond: 2.5,
  },
  {
    id: 'wm_energy_used_today',
    rel: 'wm_energy_used_today',
    sourceRel: 'energy_used/today',
    sourceId: 'worldometers',
    label: 'Energy Used Today',
    description: 'Global energy used today.',
    category: 'worldometers',
    unit: 'MWh',
    accent: '#a3e635',
    fallbackMode: 'daily',
    fallbackBaseValue: 0,
    fallbackRatePerSecond: 1_200,
  },
  {
    id: 'wm_oil_consumption_today',
    rel: 'wm_oil_consumption_today',
    sourceRel: 'oil_consumption/today',
    sourceId: 'worldometers',
    label: 'Oil Consumption Today',
    description: 'Estimated barrels consumed today.',
    category: 'worldometers',
    unit: 'barrels',
    accent: '#f59e0b',
    fallbackMode: 'daily',
    fallbackBaseValue: 0,
    fallbackRatePerSecond: 1_150,
  },
  {
    id: 'wm_co2_year',
    rel: 'wm_co2_year',
    sourceRel: 'co2_emissions/this_year',
    sourceId: 'worldometers',
    label: 'CO2 Emissions This Year',
    description: 'Estimated global CO2 emissions this year.',
    category: 'worldometers',
    unit: 'tons',
    accent: '#ef4444',
    fallbackMode: 'yearly',
    fallbackBaseValue: 0,
    fallbackRatePerSecond: 1_200,
  },
  {
    id: 'wm_water_year',
    rel: 'wm_water_year',
    sourceRel: 'water_consumed/this_year',
    sourceId: 'worldometers',
    label: 'Water Consumed This Year',
    description: 'Estimated water consumed globally this year.',
    category: 'worldometers',
    unit: 'L',
    accent: '#38bdf8',
    fallbackMode: 'yearly',
    fallbackBaseValue: 0,
    fallbackRatePerSecond: 1_500_000,
  },
  {
    id: 'wm_forest_loss_year',
    rel: 'wm_forest_loss_year',
    sourceRel: 'forest_loss/this_year',
    sourceId: 'worldometers',
    label: 'Forest Loss This Year',
    description: 'Estimated forest area lost this year.',
    category: 'worldometers',
    unit: 'ha',
    accent: '#84cc16',
    fallbackMode: 'yearly',
    fallbackBaseValue: 0,
    fallbackRatePerSecond: 0.37,
  },
]

export const metricSourceRelKey = (sourceId: SourceId, sourceRel: string): string =>
  `${sourceId}:${sourceRel}`

export const INTERNET_LIVE_STATS_METRICS = METRIC_REGISTRY.filter(
  (metric) => metric.sourceId === 'internetlivestats',
)

export const WORLDMETERS_METRICS = METRIC_REGISTRY.filter(
  (metric) => metric.sourceId === 'worldometers',
)

export const METRIC_REGISTRY_BY_REL = new Map(
  METRIC_REGISTRY.map((metric) => [metric.rel, metric]),
)

export const METRIC_REGISTRY_BY_SOURCE_REL = new Map(
  METRIC_REGISTRY.map((metric) => [
    metricSourceRelKey(metric.sourceId, metric.sourceRel ?? metric.rel),
    metric,
  ]),
)
