import type { MetricDefinition, SectionDefinition, SourceId } from '../types.js'

export const SECTION_DEFINITIONS: SectionDefinition[] = [
  {
    id: 'worldometers-population',
    title: 'Worldometers Population',
    description: 'Population growth and birth-rate indicators from Worldometers.',
  },
  {
    id: 'worldometers-economics',
    title: 'Worldometers Economics',
    description: 'Public spending and production counters from Worldometers.',
  },
  {
    id: 'worldometers-society',
    title: 'Worldometers Society',
    description: 'Media, communications, and digital activity counters.',
  },
  {
    id: 'worldometers-environment',
    title: 'Worldometers Environment',
    description: 'Land use, emissions, and environmental pressure counters.',
  },
  {
    id: 'worldometers-food',
    title: 'Worldometers Food',
    description: 'Nutrition and food-related population indicators.',
  },
  {
    id: 'worldometers-water-energy',
    title: 'Worldometers Water & Energy',
    description: 'Water consumption and energy system counters.',
  },
]

export const METRIC_REGISTRY: MetricDefinition[] = [
  {
    id: 'internet_users',
    rel: 'internet_users',
    sourceId: 'internetlivestats',
    label: 'Internet Users',
    description: 'People online worldwide.',
    category: 'internet-scale',
    accent: '#38bdf8',
    fallbackMode: 'absolute',
    fallbackBaseValue: 5_450_000_000,
    fallbackRatePerSecond: 2.3,
  },
  {
    id: 'websites_total',
    rel: 'websites',
    sourceId: 'internetlivestats',
    label: 'Websites',
    description: 'Total number of websites online.',
    category: 'internet-scale',
    accent: '#22d3ee',
    fallbackMode: 'absolute',
    fallbackBaseValue: 1_180_000_000,
    fallbackRatePerSecond: 8,
  },
  {
    id: 'emails_sent_today',
    rel: 'em/today',
    sourceId: 'internetlivestats',
    label: 'Emails Sent Today',
    description: 'Emails sent from midnight to now.',
    category: 'activity',
    accent: '#c084fc',
    fallbackMode: 'daily',
    fallbackBaseValue: 0,
    fallbackRatePerSecond: 4_166_667,
  },
  {
    id: 'google_searches_today',
    rel: 'google_searches/today',
    sourceId: 'internetlivestats',
    label: 'Google Searches Today',
    description: 'Search queries made on Google today.',
    category: 'activity',
    accent: '#f472b6',
    fallbackMode: 'daily',
    fallbackBaseValue: 0,
    fallbackRatePerSecond: 162_000,
  },
  {
    id: 'blog_posts_today',
    rel: 'blog_posts/today',
    sourceId: 'internetlivestats',
    label: 'Blog Posts Today',
    description: 'Blog posts published so far today.',
    category: 'activity',
    accent: '#818cf8',
    fallbackMode: 'daily',
    fallbackBaseValue: 0,
    fallbackRatePerSecond: 80,
  },
  {
    id: 'tweets_today',
    rel: 'tweets/today',
    sourceId: 'internetlivestats',
    label: 'Tweets Today',
    description: 'Tweets posted from midnight to now.',
    category: 'activity',
    accent: '#60a5fa',
    fallbackMode: 'daily',
    fallbackBaseValue: 0,
    fallbackRatePerSecond: 5_800,
  },
  {
    id: 'youtube_videos_today',
    rel: 'youtube_videos/today',
    sourceId: 'internetlivestats',
    label: 'YouTube Videos Today',
    description: 'Videos watched on YouTube today.',
    category: 'activity',
    accent: '#f87171',
    fallbackMode: 'daily',
    fallbackBaseValue: 0,
    fallbackRatePerSecond: 57_800,
  },
  {
    id: 'instagram_photos_today',
    rel: 'instagram_photos/today',
    sourceId: 'internetlivestats',
    label: 'Instagram Photos Today',
    description: 'Photos uploaded to Instagram today.',
    category: 'activity',
    accent: '#fb7185',
    fallbackMode: 'daily',
    fallbackBaseValue: 0,
    fallbackRatePerSecond: 1_100,
  },
  {
    id: 'tumblr_posts_today',
    rel: 'tumblr_posts/today',
    sourceId: 'internetlivestats',
    label: 'Tumblr Posts Today',
    description: 'Tumblr posts created today.',
    category: 'activity',
    accent: '#a78bfa',
    fallbackMode: 'daily',
    fallbackBaseValue: 0,
    fallbackRatePerSecond: 23,
  },
  {
    id: 'facebook_active_users',
    rel: 'facebook_users',
    sourceId: 'internetlivestats',
    label: 'Facebook Active Users',
    description: 'Active users on Facebook.',
    category: 'social',
    accent: '#3b82f6',
    fallbackMode: 'absolute',
    fallbackBaseValue: 3_100_000_000,
    fallbackRatePerSecond: 1.1,
  },
  {
    id: 'google_plus_active_users',
    rel: 'google_plus_users',
    sourceRel: 'google_users',
    sourceId: 'internetlivestats',
    label: 'Google+ Active Users',
    description: 'Active users on Google+.',
    category: 'social',
    accent: '#f97316',
    fallbackMode: 'absolute',
    fallbackBaseValue: 450_000_000,
    fallbackRatePerSecond: 0.05,
  },
  {
    id: 'twitter_active_users',
    rel: 'twitter_users',
    sourceId: 'internetlivestats',
    label: 'Twitter Active Users',
    description: 'Active users on Twitter.',
    category: 'social',
    accent: '#0ea5e9',
    fallbackMode: 'absolute',
    fallbackBaseValue: 620_000_000,
    fallbackRatePerSecond: 0.35,
  },
  {
    id: 'pinterest_active_users',
    rel: 'pinterest_users',
    sourceId: 'internetlivestats',
    label: 'Pinterest Active Users',
    description: 'Active users on Pinterest.',
    category: 'social',
    accent: '#ef4444',
    fallbackMode: 'absolute',
    fallbackBaseValue: 500_000_000,
    fallbackRatePerSecond: 0.2,
  },
  {
    id: 'skype_calls_today',
    rel: 'skype_calls/today',
    sourceId: 'internetlivestats',
    label: 'Skype Calls Today',
    description: 'Skype calls placed so far today.',
    category: 'social',
    accent: '#38bdf8',
    fallbackMode: 'daily',
    fallbackBaseValue: 0,
    fallbackRatePerSecond: 1_750,
  },
  {
    id: 'websites_hacked_today',
    rel: 'websites_hacked/today',
    sourceId: 'internetlivestats',
    label: 'Websites Hacked Today',
    description: 'Sites reportedly hacked so far today.',
    category: 'infrastructure',
    accent: '#f43f5e',
    fallbackMode: 'daily',
    fallbackBaseValue: 0,
    fallbackRatePerSecond: 0.35,
  },
  {
    id: 'computers_sold_today',
    rel: 'computers_sold/today',
    sourceId: 'internetlivestats',
    label: 'Computers Sold Today',
    description: 'Computers sold worldwide today.',
    category: 'infrastructure',
    accent: '#22c55e',
    fallbackMode: 'daily',
    fallbackBaseValue: 0,
    fallbackRatePerSecond: 5.8,
  },
  {
    id: 'smartphones_sold_today',
    rel: 'smartphones_sold/today',
    sourceId: 'internetlivestats',
    label: 'Smartphones Sold Today',
    description: 'Smartphones sold worldwide today.',
    category: 'infrastructure',
    accent: '#14b8a6',
    fallbackMode: 'daily',
    fallbackBaseValue: 0,
    fallbackRatePerSecond: 46.3,
  },
  {
    id: 'tablets_sold_today',
    rel: 'tablets_sold/today',
    sourceId: 'internetlivestats',
    label: 'Tablets Sold Today',
    description: 'Tablets sold worldwide today.',
    category: 'infrastructure',
    accent: '#84cc16',
    fallbackMode: 'daily',
    fallbackBaseValue: 0,
    fallbackRatePerSecond: 2.3,
  },
  {
    id: 'internet_traffic_today',
    rel: 'internet_traffic/today',
    sourceId: 'internetlivestats',
    label: 'Internet Traffic Today',
    description: 'Data moved over the internet today.',
    category: 'infrastructure',
    unit: 'GB',
    accent: '#f59e0b',
    fallbackMode: 'daily',
    fallbackBaseValue: 0,
    fallbackRatePerSecond: 5_900,
  },
  {
    id: 'internet_power_today',
    rel: 'power_internet/today',
    sourceId: 'internetlivestats',
    label: 'Internet Electricity Used',
    description: 'Electricity consumed by internet activity today.',
    category: 'infrastructure',
    unit: 'MWh',
    accent: '#a3e635',
    fallbackMode: 'daily',
    fallbackBaseValue: 0,
    fallbackRatePerSecond: 5.5,
  },
  {
    id: 'internet_co2_today',
    rel: 'co2_internet/today',
    sourceId: 'internetlivestats',
    label: 'Internet CO2 Emissions',
    description: 'Estimated internet-related CO2 emissions today.',
    category: 'infrastructure',
    unit: 'tons',
    accent: '#fb7185',
    fallbackMode: 'daily',
    fallbackBaseValue: 0,
    fallbackRatePerSecond: 1.5,
  },
  {
    id: 'wm_current_population',
    rel: 'wm_current_population',
    sourceRel: 'current_population',
    sourceId: 'worldometers',
    label: 'World Population',
    description: 'Current estimated world population.',
    category: 'worldometers-population',
    accent: '#22d3ee',
  },
  {
    id: 'wm_births_year',
    rel: 'wm_births_year',
    sourceRel: 'births_this_year',
    sourceId: 'worldometers',
    label: 'Births This Year',
    description: 'Estimated births since the start of the year.',
    category: 'worldometers-population',
    accent: '#fbbf24',
  },
  {
    id: 'wm_births_today',
    rel: 'wm_births_today',
    sourceRel: 'births_today',
    sourceId: 'worldometers',
    label: 'Births Today',
    description: 'Estimated births since midnight.',
    category: 'worldometers-population',
    accent: '#fbbf24',
  },
  {
    id: 'wm_growth_year',
    rel: 'wm_growth_year',
    sourceRel: 'absolute_growth_year',
    sourceId: 'worldometers',
    label: 'Population Growth This Year',
    description: 'Estimated net population growth this year.',
    category: 'worldometers-population',
    accent: '#34d399',
  },
  {
    id: 'wm_growth_today',
    rel: 'wm_growth_today',
    sourceRel: 'absolute_growth',
    sourceId: 'worldometers',
    label: 'Population Growth Today',
    description: 'Estimated net growth since midnight.',
    category: 'worldometers-population',
    accent: '#34d399',
  },
  {
    id: 'wm_public_healthcare_today',
    rel: 'wm_public_healthcare_today',
    sourceRel: 'gov_expenditures_health/today',
    sourceId: 'worldometers',
    label: 'Public Healthcare Spend Today',
    description: 'Global public healthcare expenditure today.',
    category: 'worldometers-economics',
    unit: 'USD',
    accent: '#22d3ee',
  },
  {
    id: 'wm_public_education_today',
    rel: 'wm_public_education_today',
    sourceRel: 'gov_expenditures_education/today',
    sourceId: 'worldometers',
    label: 'Public Education Spend Today',
    description: 'Global public education expenditure today.',
    category: 'worldometers-economics',
    unit: 'USD',
    accent: '#818cf8',
  },
  {
    id: 'wm_public_military_today',
    rel: 'wm_public_military_today',
    sourceRel: 'gov_expenditures_military/today',
    sourceId: 'worldometers',
    label: 'Public Military Spend Today',
    description: 'Global public military expenditure today.',
    category: 'worldometers-economics',
    unit: 'USD',
    accent: '#f97316',
  },
  {
    id: 'wm_cars_produced_year',
    rel: 'wm_cars_produced_year',
    sourceRel: 'automobile_produced/this_year',
    sourceId: 'worldometers',
    label: 'Cars Produced This Year',
    description: 'Estimated cars produced this year.',
    category: 'worldometers-economics',
    accent: '#f59e0b',
  },
  {
    id: 'wm_bikes_produced_year',
    rel: 'wm_bikes_produced_year',
    sourceRel: 'bicycle_produced/this_year',
    sourceId: 'worldometers',
    label: 'Bicycles Produced This Year',
    description: 'Estimated bicycles produced this year.',
    category: 'worldometers-economics',
    accent: '#84cc16',
  },
  {
    id: 'wm_computers_sold_year',
    rel: 'wm_computers_sold_year',
    sourceRel: 'computers_sold/this_year',
    sourceId: 'worldometers',
    label: 'Computers Sold This Year',
    description: 'Estimated computers sold this year.',
    category: 'worldometers-economics',
    accent: '#38bdf8',
  },
  {
    id: 'wm_books_published_year',
    rel: 'wm_books_published_year',
    sourceRel: 'books_published/this_year',
    sourceId: 'worldometers',
    label: 'Book Titles Published This Year',
    description: 'New book titles published this year.',
    category: 'worldometers-society',
    accent: '#a78bfa',
  },
  {
    id: 'wm_newspapers_today',
    rel: 'wm_newspapers_today',
    sourceRel: 'newspapers_circulated/today',
    sourceId: 'worldometers',
    label: 'Newspapers Circulated Today',
    description: 'Estimated newspapers circulated today.',
    category: 'worldometers-society',
    accent: '#f472b6',
  },
  {
    id: 'wm_tv_sold_today',
    rel: 'wm_tv_sold_today',
    sourceRel: 'tv/today',
    sourceId: 'worldometers',
    label: 'TV Sets Sold Today',
    description: 'Estimated TV sets sold globally today.',
    category: 'worldometers-society',
    accent: '#60a5fa',
  },
  {
    id: 'wm_cellphones_sold_today',
    rel: 'wm_cellphones_sold_today',
    sourceRel: 'cellular/today',
    sourceId: 'worldometers',
    label: 'Cell Phones Sold Today',
    description: 'Estimated cellular phones sold today.',
    category: 'worldometers-society',
    accent: '#14b8a6',
  },
  {
    id: 'wm_videogame_spend_today',
    rel: 'wm_videogame_spend_today',
    sourceRel: 'videogames/today',
    sourceId: 'worldometers',
    label: 'Video Game Spend Today',
    description: 'Money spent on video games today.',
    category: 'worldometers-society',
    unit: 'USD',
    accent: '#c084fc',
  },
  {
    id: 'wm_internet_users_today',
    rel: 'wm_internet_users_today',
    sourceRel: 'internet_users',
    sourceId: 'worldometers',
    label: 'Internet Users',
    description: 'Estimated internet users worldwide.',
    category: 'worldometers-society',
    accent: '#22d3ee',
  },
  {
    id: 'wm_emails_today',
    rel: 'wm_emails_today',
    sourceRel: 'em/today',
    sourceId: 'worldometers',
    label: 'Emails Sent Today',
    description: 'Estimated global emails sent today.',
    category: 'worldometers-society',
    accent: '#38bdf8',
  },
  {
    id: 'wm_blog_posts_today',
    rel: 'wm_blog_posts_today',
    sourceRel: 'blog_posts/today',
    sourceId: 'worldometers',
    label: 'Blog Posts Today',
    description: 'Estimated blog posts published today.',
    category: 'worldometers-society',
    accent: '#818cf8',
  },
  {
    id: 'wm_tweets_today',
    rel: 'wm_tweets_today',
    sourceRel: 'tweets/today',
    sourceId: 'worldometers',
    label: 'Tweets Sent Today',
    description: 'Estimated tweets posted today.',
    category: 'worldometers-society',
    accent: '#f472b6',
  },
  {
    id: 'wm_google_searches_today',
    rel: 'wm_google_searches_today',
    sourceRel: 'google_searches/today',
    sourceId: 'worldometers',
    label: 'Google Searches Today',
    description: 'Estimated Google searches today.',
    category: 'worldometers-society',
    accent: '#f59e0b',
  },
  {
    id: 'wm_forest_loss_year',
    rel: 'wm_forest_loss_year',
    sourceRel: 'forest_loss/this_year',
    sourceId: 'worldometers',
    label: 'Forest Loss This Year',
    description: 'Estimated forest area lost this year.',
    category: 'worldometers-environment',
    unit: 'ha',
    accent: '#84cc16',
  },
  {
    id: 'wm_soil_erosion_year',
    rel: 'wm_soil_erosion_year',
    sourceRel: 'soil_erosion/this_year',
    sourceId: 'worldometers',
    label: 'Land Lost to Soil Erosion',
    description: 'Estimated land lost to soil erosion this year.',
    category: 'worldometers-environment',
    unit: 'ha',
    accent: '#f59e0b',
  },
  {
    id: 'wm_energy_used_today',
    rel: 'wm_energy_used_today',
    sourceRel: 'energy_used/today',
    sourceId: 'worldometers',
    label: 'Energy Used Today',
    description: 'Global energy used today.',
    category: 'worldometers-water-energy',
    unit: 'MWh',
    accent: '#a3e635',
  },
  {
    id: 'wm_oil_consumption_today',
    rel: 'wm_oil_consumption_today',
    sourceRel: 'oil_consumption/today',
    sourceId: 'worldometers',
    label: 'Oil Consumption Today',
    description: 'Estimated barrels consumed today.',
    category: 'worldometers-water-energy',
    unit: 'barrels',
    accent: '#f59e0b',
  },
  {
    id: 'wm_co2_year',
    rel: 'wm_co2_year',
    sourceRel: 'co2_emissions/this_year',
    sourceId: 'worldometers',
    label: 'CO2 Emissions This Year',
    description: 'Estimated global CO2 emissions this year.',
    category: 'worldometers-environment',
    unit: 'tons',
    accent: '#ef4444',
  },
  {
    id: 'wm_desertification_year',
    rel: 'wm_desertification_year',
    sourceRel: 'desert_land_formed/this_year',
    sourceId: 'worldometers',
    label: 'Desertification This Year',
    description: 'Estimated desert land formed this year.',
    category: 'worldometers-environment',
    unit: 'ha',
    accent: '#f97316',
  },
  {
    id: 'wm_toxic_chemicals_year',
    rel: 'wm_toxic_chemicals_year',
    sourceRel: 'tox_chem/this_year',
    sourceId: 'worldometers',
    label: 'Toxic Chemicals Released',
    description: 'Estimated toxic chemicals released this year.',
    category: 'worldometers-environment',
    unit: 'tons',
    accent: '#f43f5e',
  },
  {
    id: 'wm_undernourished_population',
    rel: 'wm_undernourished_population',
    sourceRel: 'undernourished',
    sourceId: 'worldometers',
    label: 'Undernourished Population',
    description: 'Estimated undernourished people worldwide.',
    category: 'worldometers-food',
    accent: '#f59e0b',
  },
  {
    id: 'wm_overweight_population',
    rel: 'wm_overweight_population',
    sourceRel: 'overweight',
    sourceId: 'worldometers',
    label: 'Overweight Population',
    description: 'Estimated overweight people worldwide.',
    category: 'worldometers-food',
    accent: '#a78bfa',
  },
  {
    id: 'wm_obese_population',
    rel: 'wm_obese_population',
    sourceRel: 'obese',
    sourceId: 'worldometers',
    label: 'Obese Population',
    description: 'Estimated obese people worldwide.',
    category: 'worldometers-food',
    accent: '#fb7185',
  },
  {
    id: 'wm_obesity_spend_today',
    rel: 'wm_obesity_spend_today',
    sourceRel: 'obesity_spending/today',
    sourceId: 'worldometers',
    label: 'Obesity-Related Spend (US) Today',
    description: 'Money spent on obesity-related diseases in the US today.',
    category: 'worldometers-food',
    unit: 'USD',
    accent: '#f43f5e',
  },
  {
    id: 'wm_weight_loss_spend_today',
    rel: 'wm_weight_loss_spend_today',
    sourceRel: 'spending_on_weight_loss/today',
    sourceId: 'worldometers',
    label: 'Weight-Loss Program Spend (US)',
    description: 'Money spent on US weight-loss programs today.',
    category: 'worldometers-food',
    unit: 'USD',
    accent: '#ec4899',
  },
  {
    id: 'wm_water_year',
    rel: 'wm_water_year',
    sourceRel: 'water_consumed/this_year',
    sourceId: 'worldometers',
    label: 'Water Consumed This Year',
    description: 'Estimated water consumed globally this year.',
    category: 'worldometers-water-energy',
    unit: 'million L',
    accent: '#38bdf8',
  },
  {
    id: 'wm_no_safe_water_population',
    rel: 'wm_no_safe_water_population',
    sourceRel: 'nowater_population',
    sourceId: 'worldometers',
    label: 'No Safe Drinking Water Access',
    description: 'Estimated population without a safe drinking water source.',
    category: 'worldometers-water-energy',
    accent: '#0ea5e9',
  },
  {
    id: 'wm_energy_nonrenewable_today',
    rel: 'wm_energy_nonrenewable_today',
    sourceRel: 'energy_nonren/today',
    sourceId: 'worldometers',
    label: 'Non-Renewable Energy Today',
    description: 'Energy used today from non-renewable sources.',
    category: 'worldometers-water-energy',
    unit: 'MWh',
    accent: '#f97316',
  },
  {
    id: 'wm_energy_renewable_today',
    rel: 'wm_energy_renewable_today',
    sourceRel: 'energy_ren/today',
    sourceId: 'worldometers',
    label: 'Renewable Energy Today',
    description: 'Energy used today from renewable sources.',
    category: 'worldometers-water-energy',
    unit: 'MWh',
    accent: '#22c55e',
  },
  {
    id: 'wm_solar_energy_today',
    rel: 'wm_solar_energy_today',
    sourceRel: 'solar_energy/today',
    sourceId: 'worldometers',
    label: 'Solar Energy Striking Earth Today',
    description: 'Estimated solar energy reaching Earth today.',
    category: 'worldometers-water-energy',
    unit: 'MWh',
    accent: '#facc15',
  },
  {
    id: 'wm_oil_reserves',
    rel: 'wm_oil_reserves',
    sourceRel: 'oil_reserves',
    sourceId: 'worldometers',
    label: 'Oil Reserves Remaining',
    description: 'Estimated oil reserves remaining worldwide.',
    category: 'worldometers-water-energy',
    unit: 'barrels',
    accent: '#f59e0b',
  },
  {
    id: 'wm_oil_days_left',
    rel: 'wm_oil_days_left',
    sourceRel: 'oil_days',
    sourceId: 'worldometers',
    label: 'Days to End of Oil',
    description: 'Estimated days until oil reserves run out.',
    category: 'worldometers-water-energy',
    unit: 'days',
    accent: '#f97316',
  },
  {
    id: 'wm_gas_reserves',
    rel: 'wm_gas_reserves',
    sourceRel: 'gas_reserves',
    sourceId: 'worldometers',
    label: 'Natural Gas Reserves Remaining',
    description: 'Estimated natural gas reserves remaining.',
    category: 'worldometers-water-energy',
    unit: 'boe',
    accent: '#22c55e',
  },
  {
    id: 'wm_gas_days_left',
    rel: 'wm_gas_days_left',
    sourceRel: 'gas_days',
    sourceId: 'worldometers',
    label: 'Days to End of Natural Gas',
    description: 'Estimated days until natural gas reserves run out.',
    category: 'worldometers-water-energy',
    unit: 'days',
    accent: '#16a34a',
  },
  {
    id: 'wm_coal_reserves',
    rel: 'wm_coal_reserves',
    sourceRel: 'coal_reserves',
    sourceId: 'worldometers',
    label: 'Coal Reserves Remaining',
    description: 'Estimated coal reserves remaining.',
    category: 'worldometers-water-energy',
    unit: 'boe',
    accent: '#64748b',
  },
  {
    id: 'wm_coal_days_left',
    rel: 'wm_coal_days_left',
    sourceRel: 'coal_days',
    sourceId: 'worldometers',
    label: 'Days to End of Coal',
    description: 'Estimated days until coal reserves run out.',
    category: 'worldometers-water-energy',
    unit: 'days',
    accent: '#475569',
  },
]

export const metricSourceRelKey = (sourceId: SourceId, sourceRel: string): string =>
  `${sourceId}:${sourceRel}`

export const INTERNET_LIVE_STATS_METRICS = METRIC_REGISTRY.filter(
  (metric) => metric.sourceId === 'internetlivestats',
)

export const WORLDMETERS_METRICS = METRIC_REGISTRY.filter(
  (metric) => metric.sourceId === 'worldometers',
)

export const METRIC_REGISTRY_BY_REL = new Map(
  METRIC_REGISTRY.map((metric) => [metric.rel, metric]),
)

export const METRIC_REGISTRY_BY_SOURCE_REL = new Map(
  METRIC_REGISTRY.map((metric) => [
    metricSourceRelKey(metric.sourceId, metric.sourceRel ?? metric.rel),
    metric,
  ]),
)
